apiVersion: apps/v1
kind: Deployment
metadata:
  name: sublink-nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sublink-nginx
  template:
    metadata:
      labels:
        app: sublink-nginx
    spec:
      volumes:
      - name: sublink-nginx-config
        configMap:
          name: sublink-nginx-config
      containers:
      - name: nginx
        image: nginx:1.17.9
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /etc/nginx/conf.d
            name: sublink-nginx-config
            readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: sublink-reverse-proxy
  labels:
    app: sublink-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31693
    name: sublink-nginx
  selector:
    app: sublink-nginx
