apiVersion: v1
kind: Service
metadata:
  name: sublink-parachain-alice
  labels:
    app: sublink-parachain-alice
spec:
  selector:
    app: sublink-parachain-alice
  ports:
  - port: 40333
    targetPort: 40333
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sublink-parachain-ws
  labels:
    node: sublink-parachain
spec:
  selector:
    node: sublink-parachain
  ports:
  - port: 8844
    targetPort: 8844
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sublink-parachain-2001
  labels:
    app: sublink-parachain-2001
spec:
  selector:
    app: sublink-parachain-2001
  ports:
  - port: 40334
    targetPort: 40333
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sublink-parachain-ws-2001
  labels:
    node: sublink-parachain-2001
spec:
  selector:
    node: sublink-parachain-2001
  ports:
  - port: 8845
    targetPort: 8844
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sublink-apps
  labels:
    node: sublink-apps
spec:
  selector:
    node: sublink-apps
  ports:
  - port: 3000
    targetPort: 80
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sublink-contracts
  labels:
    node: sublink-contracts
spec:
  selector:
    node: sublink-contracts
  ports:
  - port: 8081
    targetPort: 80
    protocol: TCP
